models/Employee.php
<?php

namespace app\models;

/**
 * This is the model class for table "test_task_employee".
 *
 * @property int $id
 * @property string $name
 * @property string $surname
 * @property double $salary
 *
 * @property WeekDay[] $weekDays
 */
class Employee extends \yii\db\ActiveRecord
{

    public $bonus;
    public $sumCalls;
    public $fullSalary;

    public static $bonusTypes = [
        'START' => ['step' => 100, 'bonus' => 100, 'desk' => 'Begin'],
        'MIDDLE' => ['step' => 200, 'bonus' => 200, 'desk' => 'Middle'],
        'HIGH' => ['step' => 300, 'bonus' => 300, 'desk' => 'High'],
    ];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%employee}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'surname', 'salary'], 'required'],
            [['salary'], 'number'],
            [['name', 'surname'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'surname' => 'Surname',
            'salary' => 'Salary',
        ];
    }

    public function getFullName() {
        return $this->name . ' ' . $this->surname;
    }

    public function extraFields()
    {
        return [
            'fullName' => $this->fullName
        ];
    }

    /**
     * Get all week days for the period
     * @param $begin object DateTime or date string
     * @param $end object DateTime or date string
     * @return '\yii\db\ActiveQuery WeekDay
     */
    public function getWeekDays($month)
    {
        $begin = new \DateTime($month);
        $end = clone $begin;
        $end->modify('+1 month');
        $days = $this->hasMany(WeekDay::className(), ['employee_id' => 'id'])
                     ->where(['>=', 'date', $begin->format('Y-m-d')])
                     ->andWhere(['<', 'date', $end->format('Y-m-d')])
                     ->all();
        $this->calculateSalary($days);
        return $days;
    }

    /**
     * Calculate $fullSalary, $bonus, $sumCall
     * @param $days \yii\db\ActiveQuery weekDay
     */
    public function calculateSalary($days)
    {
        if ($days) {
            $this->sumCalls = array_reduce($days, function ($sum, $day) { return $sum + $day->count_calls; }, 0);
            $this->bonus = $this->getBonus();
            $this->fullSalary = $this->bonus['bonus'] * $this->sumCalls + $this->salary;
        }
    }

    private function getBonus()
    {
        foreach (array_reverse(self::$bonusTypes) as $item) {
            if ($this->sumCalls >= $item['step']) {
                return $item;
            }
        }
    }
}

controllers/EmployeeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Employee;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EmployeeController implements the CRUD actions for Employee model.
 */
class EmployeeController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Employee models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Employee::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Employee model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $employee = $this->findModel($id);

        $month = Yii::$app->request->post('month');

        if (empty($month)) {
            $month = date('Y-m');
        }

        return $this->render('view', [
            'model' => $employee,
            'month' => $month,
            'weekDays' => $employee->getWeekDays($month),
        ]);
    }

    /**
     * Creates a new Employee model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Employee();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Employee model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Employee model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionCalculateBonus($month) {

    }

    /**
     * Finds the Employee model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Employee the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Employee::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/employee/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Employee */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employee-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'salary')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/employee/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Employee */

$this->title = 'Create Employee';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employee-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/employee/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Employees';
?>
<div class="employee-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Employee', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'format' => 'raw',
                'label' => 'Full name',
                'value' => function($employee) {
                    return Html::a($employee->getFullName(), ['employee/view', 'id' => $employee->id]);
                }
            ],
            'salary',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/employee/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Employee */

$this->title = 'Update Employee: ' .  $model->name . ' ' . $model->surname;
$this->params['breadcrumbs'][] = ['label' => $model->getFullName(), 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="employee-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/employee/view.php
<?php

use yii\helpers\Html;
use yii\jui\DatePicker;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Employee */
/* @var $month string */
/* @var $weekDays */

$this->title = $model->getFullName();
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="employee-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?php $form = ActiveForm::begin() ?>

        <label for="month">Select Month:</label>
        <?= DatePicker::widget([
            'language' => 'ru',
            'dateFormat' => 'php:Y-m',
            'value' => $month,
            'name' => 'month',
            'options' => [
                'class' => 'form-control',
                'name' => 'month',
                'id' => 'month',
                'required' => true,
            ],
            'clientOptions' => [
                'dateFormat' => 'yy-mm',
                'changeMonth'=> true,
                'changeYear'=> true,
            ],
        ]);?>

        <div class="form-group">
            <?= Html::submitButton('Show information for the month', ['class' => 'btn btn-success']) ?>
        </div>

    <?php ActiveForm::end() ?>



    <br>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            'surname',
            'salary',
            [
                'label' => 'WeekDays',
                'format' => 'raw',
                'value' => join(
                        '<br>',
                        array_map(
                            function($weekDay){
                                return Html::a(
                                        $weekDay->date . ' | ' . $weekDay->count_calls . ' | ' . $weekDay->getPresenceView(),
                                        ['week-day/view', 'id' => $weekDay->id],
                                        ['target' => 'blank']
                                );
                            },
                            $weekDays
                    )
                )
            ],

            [
                'label' => 'Salary + Bonus',
                'value' => $model->fullSalary
            ],

            [
                'label' => 'Bonus',
                'value' =>  $model->bonus? $model->bonus['desk'] . ' | ' . $model->bonus['bonus'] . ' / call': 0
            ],

            [
                'label' => 'Sum calls',
                'value' => $model->sumCalls
            ],

        ],
    ]) ?>

</div>